### ISSUE TITLE
Failure to run ObjectDetectionYoloRKNN on any 2.8.* and 2.9.* version of codeproject-ai available on docker hub

### ISSUE THREAD

**Issue by grinco** [codeproject/CodeProject.AI-ObjectDetectionYoloRKNN#2]
Hi, I tried upgrading the docker image to latest version 2.9.5 - object detection stopped working. I tried downgrading back to 2.9.2 - it did not work. Tried a clean install on 2.8.0. 2.9.2, 2.9.4 and 2.9.5 - get the same result:
```
00:12:38:Started Object Detection (YOLOv5 RKNN) module
00:12:39:objectdetection_fd_rknn_adapter.py: A module that was compiled using NumPy 1.x cannot be run in
00:12:39:objectdetection_fd_rknn_adapter.py: NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
00:12:39:objectdetection_fd_rknn_adapter.py: versions of NumPy, modules must be compiled with NumPy 2.0.
00:12:39:objectdetection_fd_rknn_adapter.py: Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
00:12:39:objectdetection_fd_rknn_adapter.py: If you are a user of the module, the easiest solution will be to
00:12:39:objectdetection_fd_rknn_adapter.py: downgrade to 'numpy<2' or try to upgrade the affected module.
00:12:39:objectdetection_fd_rknn_adapter.py: We expect that some modules will need time to support NumPy 2.
00:12:39:objectdetection_fd_rknn_adapter.py: Traceback (most recent call last):  File "/app/modules/ObjectDetectionYoloRKNN/objectdetection_fd_rknn_adapter.py", line 7, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     from codeproject_ai_sdk import RequestData, ModuleRunner, LogMethod, JSON
00:12:39:objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/bin/linux/python39/venv/lib/python3.9/site-packages/codeproject_ai_sdk/__init__.py", line 4, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     from .module_runner import ModuleRunner
00:12:39:objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/bin/linux/python39/venv/lib/python3.9/site-packages/codeproject_ai_sdk/module_runner.py", line 36, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     from .request_data   import RequestData
00:12:39:objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/bin/linux/python39/venv/lib/python3.9/site-packages/codeproject_ai_sdk/request_data.py", line 15, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     import cv2 as cv
00:12:39:objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/bin/linux/python39/venv/lib/python3.9/site-packages/cv2/__init__.py", line 5, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     from .cv2 import *
00:12:39:objectdetection_fd_rknn_adapter.py: AttributeError: _ARRAY_API not found
00:12:39:objectdetection_fd_rknn_adapter.py: Using PIL for image manipulation (Either OpenCV or numpy not available for this module)
00:12:39:objectdetection_fd_rknn_adapter.py: Traceback (most recent call last):
00:12:39:objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/objectdetection_fd_rknn_adapter.py", line 14, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     from objectdetection_fd_rknn import init_detect, do_detect
00:12:39:objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/objectdetection_fd_rknn.py", line 26, in 
00:12:39:objectdetection_fd_rknn_adapter.py:     from module_logging import LogMethod
00:12:39:objectdetection_fd_rknn_adapter.py: ModuleNotFoundError: No module named 'module_logging'
```

Looks like it may be something with the AI server itself, not sure. Would appreciate your help.

**Comment by grinco** [comment]
Looks like changing https://github.com/codeproject/CodeProject.AI-ObjectDetectionYoloRKNN/blob/d2520afc1f89ae9f8de92202c5e564a1966a9496/objectdetection_fd_rknn.py#L26 
to 
`from codeproject_ai_sdk import LogMethod`
solves the issue for me, but I'm not sure if it's a proper fix, so sharing it here instead of raising a PR.

**Comment by ChrisMaunder** [comment]
Perfect! Thank you. I'll make the fix as soon as I get a chance

(Update: done)
